/*
--------------------------------------------------
Sistema de Passagens Aéreas - Van Linhas Aéreas
Disciplina: Banco de Dados
Aluna: Vanessa Toledo
--------------------------------------------------
*/

/* ==================================================
   TABELA PASSAGEIRO
================================================== */

CREATE TABLE passageiro (
    id_passageiro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(120) NOT NULL,
    data_nascimento DATE NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE
);


/* ==================================================
   TABELA AEROPORTO
================================================== */

CREATE TABLE aeroporto (
    id_aeroporto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo_iata VARCHAR(10) NOT NULL UNIQUE,
    nome VARCHAR(120) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    pais VARCHAR(100) NOT NULL
);


/* ==================================================
   TABELA AERONAVE
================================================== */

CREATE TABLE aeronave (
    id_aeronave BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo VARCHAR(20) NOT NULL UNIQUE,
    modelo VARCHAR(100) NOT NULL,
    capacidade INTEGER NOT NULL,

    CONSTRAINT ck_aeronave_capacidade
    CHECK (capacidade > 0)
);


/* ==================================================
   TABELA VOO
================================================== */

CREATE TABLE voo (
    id_voo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    numero_voo VARCHAR(20) NOT NULL,

    data_hora_partida TIMESTAMP NOT NULL,
    data_hora_chegada TIMESTAMP NOT NULL,

    preco_base NUMERIC(10,2) NOT NULL,

    id_aeroporto_origem BIGINT NOT NULL,
    id_aeroporto_destino BIGINT NOT NULL,
    id_aeronave BIGINT NOT NULL,

    CONSTRAINT voo_id_aeroporto_origem_fkey
    FOREIGN KEY (id_aeroporto_origem)
    REFERENCES aeroporto(id_aeroporto),

    CONSTRAINT voo_id_aeroporto_destino_fkey
    FOREIGN KEY (id_aeroporto_destino)
    REFERENCES aeroporto(id_aeroporto),

    CONSTRAINT voo_id_aeronave_fkey
    FOREIGN KEY (id_aeronave)
    REFERENCES aeronave(id_aeronave),

    CONSTRAINT ck_voo_preco_base
    CHECK (preco_base >= 0),

    CONSTRAINT ck_voo_origem_destino
    CHECK (id_aeroporto_origem <> id_aeroporto_destino),

    CONSTRAINT ck_voo_datas
    CHECK (data_hora_chegada > data_hora_partida)
);


/* ==================================================
   TABELA RESERVA
================================================== */

CREATE TABLE reserva (
    id_reserva BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    data_reserva DATE NOT NULL,
    status VARCHAR(30) NOT NULL,

    id_passageiro BIGINT NOT NULL,

    CONSTRAINT reserva_id_passageiro_fkey
    FOREIGN KEY (id_passageiro)
    REFERENCES passageiro(id_passageiro),

    CONSTRAINT ck_reserva_status
    CHECK (
        status IN (
            'Pendente',
            'Confirmada',
            'Cancelada',
            'Alterada'
        )
    )
);


/* ==================================================
   TABELA RESERVA_VOO
================================================== */

CREATE TABLE reserva_voo (
    id_reserva BIGINT NOT NULL,
    id_voo BIGINT NOT NULL,

    assento VARCHAR(10) NOT NULL,
    preco_pago NUMERIC(10,2) NOT NULL,

    CONSTRAINT reserva_voo_pkey
    PRIMARY KEY (id_reserva, id_voo),

    CONSTRAINT reserva_voo_id_reserva_fkey
    FOREIGN KEY (id_reserva)
    REFERENCES reserva(id_reserva),

    CONSTRAINT reserva_voo_id_voo_fkey
    FOREIGN KEY (id_voo)
    REFERENCES voo(id_voo),

    CONSTRAINT ck_reserva_voo_preco_pago
    CHECK (preco_pago >= 0)
);


/* ==================================================
   DADOS FICTÍCIOS - VAN LINHAS AÉREAS
================================================== */

INSERT INTO passageiro
(cpf, nome, data_nascimento, email)
VALUES
('06778016612', 'Vanessa Toledo', '1988-08-30', 'vanessat@vanlinhas.com'),
('31663058822', 'Daniela de Paula', '1983-05-12', 'danielap@vanlinhas.com'),
('47766412837', 'Miguel de Paula', '2011-04-25', 'miguelp@vanlinhas.com');


INSERT INTO aeroporto
(codigo_iata, nome, cidade, pais)
VALUES
('UDI', 'Aeroporto Ten. Cel. Aviador César Bombonato', 'Uberlândia', 'Brasil'),
('GRU', 'Aeroporto Internacional de Guarulhos', 'São Paulo', 'Brasil'),
('BSB', 'Aeroporto Internacional de Brasília', 'Brasília', 'Brasil'),
('REC', 'Aeroporto Internacional do Recife', 'Recife', 'Brasil');


INSERT INTO aeronave
(codigo, modelo, capacidade)
VALUES
('VLA001', 'Airbus A666', 150),
('VLA002', 'Boeing 777-888', 180);


INSERT INTO voo
(
    numero_voo,
    data_hora_partida,
    data_hora_chegada,
    preco_base,
    id_aeroporto_origem,
    id_aeroporto_destino,
    id_aeronave
)
VALUES
('VAN101', '2026-09-10 08:00:00', '2026-09-10 09:20:00', 350.00, 1, 2, 1),
('VAN102', '2026-09-10 11:00:00', '2026-09-10 14:00:00', 450.00, 2, 4, 1),
('VAN201', '2026-09-11 07:00:00', '2026-09-11 08:00:00', 280.00, 1, 3, 2),
('VAN202', '2026-09-11 09:00:00', '2026-09-11 11:30:00', 390.00, 3, 4, 2);


INSERT INTO reserva
(data_reserva, status, id_passageiro)
VALUES
('2026-09-01', 'Confirmada', 1),
('2026-09-02', 'Pendente', 2),
('2026-09-03', 'Alterada', 3);


INSERT INTO reserva_voo
(id_reserva, id_voo, assento, preco_pago)
VALUES
(1, 1, '1A', 320.00),
(1, 2, '1A', 420.00),
(2, 3, '8C', 260.00),
(3, 3, '10B', 250.00),
(3, 4, '10B', 380.00);
